### ISSUE TITLE
gcc installation path does not work with master branch in cmake hexagon

### ISSUE THREAD

**Issue by skye-AL** [ATLFlight/cross_toolchain#14]
@mcharleb I commented your last commit to the cross_toolchain library and now saw another user having the same problem as I faced. Therefore I post my comment here again:

Great work, I really appreciate that you keep this repository up to date with the newest software available. However, the change from:

echo "Unpacking cross compiler..."
-		tar -C ${HEXAGON_SDK_ROOT} -xJf downloads/${GCC_2014}.tar.xz
-		mv ${HEXAGON_SDK_ROOT}/${GCC_2014} ${HEXAGON_SDK_ROOT}/${GCC_2014}_linux
+		mkdir -p ${HOME}/Qualcomm/ARM_Tools

to

+		tar -C ${HOME}/Qualcomm/ARM_Tools -xJf downloads/${GCC_2014}.tar.xz
+		mv ${HOME}/Qualcomm/ARM_Tools/${GCC_2014} ${ARM_TOOLS_ROOT}

should also be considered in the cmake_hexagon repository, Toolchain-arm-linux-gnueabihf.cmake

find_program(C_COMPILER arm-linux-gnueabihf-gcc
	PATHS
		${HEXAGON_SDK_ROOT}/gcc-linaro-arm-linux-gnueabihf-4.8-2013.08_linux/bin
		${HEXAGON_SDK_ROOT}/gcc-linaro-4.9-2014.11-x86_64_arm-linux-gnueabihf_linux/bin
		${HEXAGON_SDK_ROOT}/gcc-linaro-4.9-2016.02-x86_64_arm-linux-gnueabihf/bin
	NO_DEFAULT_PATH
)

**Comment by mcharleb** [comment]
@skye-AL Thanks, I'll have a look and update it.

**Comment by skye-AL** [comment]
@mcharleb super, thank you a lot and also for your work on the snapdragon in general! I wouldn't be able to use the snapdragon at all without your tools.
