### ISSUE TITLE
Conflicting paths for sysroot

### ISSUE THREAD

**Issue by julianoes** [ATLFlight/cross_toolchain#6]
The [Devguide](https://github.com/PX4/Devguide/blob/92553d97ceb021a2fd3a8ff412d5a4051298e85b/book/starting-installing-linux.md#sysroot-installation) suggests the path below for sysroot:

```
export HEXAGON_ARM_SYSROOT=${HOME}/Qualcomm/qrlinux_v1.0_sysroot
```

However, when installing the latest Flight_qrlSDK.zip from Intrinsyc, it tells me the old path at the end:

```
Make sure to set the following environment variables:
   export HEXAGON_ARM_SYSROOT=/home/julianoes/Qualcomm/Hexagon_SDK/2.0/sysroot
```

Is the Intrinsyc zip outdated?

FYI: @mcharleb

**Comment by julianoes** [comment]
I think the cause for this was that I already had the old sysroot zip extracted, so it didn't get the files from the updated zip.

**Comment by julianoes** [comment]
The problem was just a missing `exit` in the script. My old and wrong environment variable was detected but the script kept going.

**Comment by mcharleb** [comment]
@julianoes Just FYI, the current Intrinsyc Flight_qrlSDK.zip doesn't provide the additional libs and APIs for using the camera in a usable way. I'm fixing it but it will take me some time. For now the stock Trusty sysroot and the qrlSDK sysroot are basically equivalent.

**Comment by mcharleb** [comment]
@julianoes I updated the document to use the Trusty sysroot for now since the Flight_qrlSDK.zip is currently not downloadable from Intrinsyc.

**Comment by julianoes** [comment]
@mcharleb thanks for the note. Looks like it got taken down.
